version: '3'
services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
    networks:
      - hyperf_net

  mysql:
    image: mysql:8.0
    container_name: hyperf_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hyperf
      MYSQL_USER: hyperf
      MYSQL_PASSWORD: hyperf
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hyperf_net

  redis:
    image: redis:7-alpine
    container_name: hyperf_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - hyperf_net

volumes:
  mysql_data:
networks:
  hyperf_net:
    driver: bridge
